#!/usr/bin/env python

import sys
import json
import csv

helper = \
'''
Usage: pg2json.py <input.csv> <col_with_quoted_json> <output.json>

Converts a csv/tsv file containing a quoted json column
generated by csv2json into a pure json file.
'''

if len(sys.argv) != 4:
  print('Incorrect number of arguments')
  print(helper)
  exit(1)

col_with_quoted_json = int(sys.argv[2])

with open(sys.argv[1]) as in_file, open(sys.argv[3], mode='w') as out_file:
  if '.csv' in sys.argv[1]:
    delimiter = ','
  else:
    delimiter = '\t'

  csv_reader = csv.reader(in_file, delimiter=delimiter, quotechar="'")
  headers = next(csv_reader, None)
  for row in csv_reader:
    out_json = {}
    for index, header in enumerate(headers):
      if index == col_with_quoted_json:
        out_json[header] = json.loads(json.loads(row[index]))
      else:
        out_json[header] = row[index]
    out_file.write(json.dumps(out_json) + '\n')

